version: '3'

services:
  nginx:
    image: nginx:latest
    depends_on:
      app:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: test_db        
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - default

  app:
    build: .
    restart: on-failure
    expose:
      - 8000
    networks:
      - default